[package]
name = "epub"
version = "0.2.1"
authors = ["Jeremy Zheng <jitang.zheng@gmail.com>"]
description = "Parse epub book by rust."
homepage = "https://github.com/cinnabaris/epub"
license = "MIT"

[dependencies]
zip = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde-xml-rs = "0.2"
